package org.sco.composecoordinator

object TextObject {

        val lorem = """
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Ac odio tempor orci dapibus ultrices in iaculis nunc. Elit duis tristique sollicitudin nibh sit. Sit amet purus gravida quis. Morbi quis commodo odio aenean sed adipiscing. Posuere morbi leo urna molestie at elementum eu facilisis. Ultrices sagittis orci a scelerisque purus. Vel facilisis volutpat est velit. Pellentesque id nibh tortor id. Enim ut tellus elementum sagittis vitae et leo duis ut. Facilisis volutpat est velit egestas dui id ornare arcu. Nisl rhoncus mattis rhoncus urna. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin.

        Sit amet dictum sit amet. Proin libero nunc consequat interdum varius sit amet mattis. Sit amet consectetur adipiscing elit. Massa enim nec dui nunc mattis enim ut tellus elementum. Felis imperdiet proin fermentum leo vel orci porta. Quis lectus nulla at volutpat diam ut venenatis tellus in. In hac habitasse platea dictumst vestibulum. Id aliquet risus feugiat in ante. Consectetur adipiscing elit duis tristique sollicitudin nibh. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Cursus mattis molestie a iaculis at erat. Lacus sed turpis tincidunt id aliquet risus feugiat in.

        Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Tellus orci ac auctor augue mauris augue neque gravida. Turpis egestas sed tempus urna et pharetra. Id velit ut tortor pretium. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Libero enim sed faucibus turpis in eu mi. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Condimentum id venenatis a condimentum. Leo a diam sollicitudin tempor id eu. Purus viverra accumsan in nisl nisi. Adipiscing bibendum est ultricies integer quis. Amet purus gravida quis blandit turpis cursus. Turpis egestas sed tempus urna et pharetra pharetra massa. Fames ac turpis egestas maecenas pharetra. Sodales neque sodales ut etiam sit amet nisl. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Ut consequat semper viverra nam libero justo laoreet sit.

        Viverra orci sagittis eu volutpat odio facilisis. Dolor sit amet consectetur adipiscing elit ut aliquam. Convallis aenean et tortor at risus viverra. Vestibulum morbi blandit cursus risus at. Dis parturient montes nascetur ridiculus mus mauris vitae. Leo urna molestie at elementum eu facilisis sed odio morbi. Interdum varius sit amet mattis vulputate enim nulla. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. A pellentesque sit amet porttitor. Interdum consectetur libero id faucibus nisl tincidunt eget.

        Diam quam nulla porttitor massa id. Magna sit amet purus gravida quis. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Gravida rutrum quisque non tellus orci ac. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Sed turpis tincidunt id aliquet risus feugiat in ante. Magnis dis parturient montes nascetur ridiculus mus mauris. Euismod in pellentesque massa placerat duis ultricies lacus sed. Sed egestas egestas fringilla phasellus faucibus scelerisque. Arcu ac tortor dignissim convallis aenean et. At elementum eu facilisis sed odio morbi quis. Interdum velit laoreet id donec. At erat pellentesque adipiscing commodo elit at imperdiet. Arcu non sodales neque sodales ut. Sit amet aliquam id diam maecenas ultricies mi eget. Vel eros donec ac odio.
    """.trimIndent()
}